name: Building Wine 7z Package(WOW64)
run-name: ${{ github.actor }} Building Wine 7z Package(WOW64) üöÄ
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Building Wine
        env: 
          GUSER: ${{ secrets.GUSER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          UPLOADURL: ${{ secrets.UPLOADURL }}
        run: |
          # ÈÖçÁΩÆÁºñËØëÂÆπÂô®
          sudo apt update
          sudo apt install qemu-user-static aria2 debootstrap neofetch python3 curl -y
          neofetch
          sudo debootstrap --arch amd64 buster ~/debian10-amd64
          sudo aria2c -d /usr/bin -o pardus-chroot https://github.com/gfdgd-xi/deep-wine-runner/raw/main/pardus-chroot
          sudo chmod 777 /usr/bin/pardus-chroot
          sudo pardus-chroot ~/debian10-amd64
          # ÁºñËØë amd64 wine
          sudo aria2c -d ~/debian10-amd64 -o wineautobuild-action-7z.sh https://github.com/gfdgd-xi/deep-wine-runner/raw/main/wineautobuild-action-7z-wow64.sh
          git clone https://github.com/gfdgd-xi/auto-building-wine --depth=1
          sudo cp auto-building-wine/wine-version.txt ~/debian10-amd64 -rv
          sudo cp auto-building-wine/wine-url.txt ~/debian10-amd64 -rv
          sudo cp auto-building-wine/wine-type.txt ~/debian10-amd64 -rv
          sudo chroot ~/debian10-amd64 bash /wineautobuild-action-7z.sh
          # Êèê‰∫§wine
          # Ëé∑ÂèñÊï∞ÊçÆ
          url=`cat auto-building-wine/wine-url.txt`
          version=`cat auto-building-wine/wine-version.txt`
          type=`cat auto-building-wine/wine-type.txt`
          #curl -F "file=@$HOME/debian10-amd64/wine/wine-$type-wow64-$version-debian10-amd64.7z" "$UPLOADURL"
          sudo mv $HOME/debian10-amd64/wine/wine-$type-wow64-$version-debian10-amd64.7z  ~/wine-amd64.7z
      - name: upload result(Wine AMD64)
        uses: actions/upload-artifact@v1
        with:
          name: wine-wow64-debian10-amd64
          path: /home/runner/wine-amd64.7z
      - name: Config Arm Building Environment
        run: |
          cpu=$(cat /proc/cpuinfo | grep processor | wc -l)
          sudo debootstrap --arch arm64 buster ~/debian10-arm64
          sudo pardus-chroot ~/debian10-arm64
          sudo chroot ~/debian10-arm64 apt update
          sudo chroot ~/debian10-arm64 apt install git sudo make cmake -y
      - name: Build Box64
        run: |
          sudo chroot ~/debian10-arm64 git clone https://github.com/ptitSeb/box64 --depth=1
          sudo chroot ~/debian10-arm64 bash -c 'cd box64; apt build-dep . -y'
          sudo chroot ~/debian10-arm64 mkdir /install
          sudo chroot ~/debian10-arm64 bash -c 'cd box64; cmake .'
          sudo chroot ~/debian10-arm64 bash -c "cd box64; make all -j$cpu" | true
          sudo chroot ~/debian10-arm64 bash -c "cd box64; make install DESTDIR=/install -j$cpu" | true
      - name: Pack Arm 7z
        run: |
          # Ëß£Âéã
          cd /tmp
          mkdir arm-wine
          cd arm-wine
          7z x /home/runner/wine-amd64.7z
          mv bin/wine bin/wine-i386
          cp ~/auto-building-wine/wine-run.sh run.sh
          cp ~/auto-building-wine/wine-run-compatible.sh bin/wine
          chmod 777 -Rv run.sh
          chmod 777 -Rv bin/wine
          mkdir -p box64
          cp -rv ~/debian10-arm64/install/etc/box64.box64rc box64
          cp -rv ~/debian10-arm64/install/usr/lib/x86_64-linux-gnu box64
          cp -rv ~/debian10-arm64/install/usr/local/bin/box64 box64
          7z a ~/wine-box64-arm64.7z *
      - name: upload result(Wine BOX64 ARM64)
        uses: actions/upload-artifact@v1
        with:
          name: wine-wow64-box64-debian10-arm64
          path: /home/runner/wine-box64-arm64.7z