name: Push Box64
run-name: ${{ github.actor }} Push Box64 ğŸš€
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Push Box64
        env: 
          ATOMGITUSER: ${{ secrets.ATOMGITUSER }}
          ATOMGITPASSWORD: ${{ secrets.ATOMGITPASSWORD }}
        run: |
          # é…ç½®ç¼–è¯‘å®¹å™¨
          sudo apt update
          sudo apt install git -y
          git clone https://github.com/ryanfortner/box64-debs/
          cd box64-debs
          git remote set-url https://$ATOMGITUSER:$ATOMGITPASSWORD@atomgit.com/gfdgd-xi/box64-debs.git
          git push
      